# Employee Attrition Prediction Using Machine Learning

# PHASE 1: Data Understanding & Cleaning

## Project Background

Employee attrition is a major challenge for organizations because replacing experienced employees requires significant time, effort, and financial resources. High turnover can disrupt business operations, reduce productivity, lower employee morale, and increase recruitment and training costs.

This project uses the IBM HR Analytics Employee Attrition dataset to explore the factors influencing employee turnover and develop a machine learning model capable of predicting whether an employee is likely to leave the organization. The project begins with understanding the dataset, assessing its quality, and preparing it for exploratory data analysis and predictive modeling.

---

## Project Objectives

The objectives of this phase are to:

- Understand the structure and contents of the dataset.
- Assess the overall quality of the data.
- Identify missing values, duplicates, and inconsistent data types.
- Detect identifier and constant variables.
- Document data cleaning decisions.
- Prepare the dataset for Exploratory Data Analysis (EDA) and Machine Learning.

---

## Dataset Overview

- **Dataset:** IBM HR Analytics Employee Attrition & Performance
- **Prediction Task:** Binary Classification
- **Target Variable:** Attrition
- **Number of Records:** 1,470 Employees
- **Number of Variables:** 35 Features

#### Importing Libraries

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

plt.style.use('ggplot')

In [5]:
# Loading Dataset and Preview

df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")
df.head()
df.tail()
df.sample(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
812,43,No,Travel_Frequently,1082,Research & Development,27,3,Life Sciences,1,1126,3,Female,83,3,3,Manufacturing Director,1,Married,10820,11535,8,Y,No,11,3,3,80,1,18,1,3,8,7,0,1
1124,39,No,Travel_Rarely,1462,Sales,6,3,Medical,1,1588,4,Male,38,4,3,Sales Executive,3,Married,8237,4658,2,Y,No,11,3,1,80,1,11,3,3,7,6,7,6
1081,35,No,Travel_Rarely,1029,Research & Development,16,3,Life Sciences,1,1529,4,Female,91,2,3,Healthcare Representative,2,Single,8606,21195,1,Y,No,19,3,4,80,0,11,3,1,11,8,3,3
858,53,No,Travel_Rarely,1223,Research & Development,7,2,Medical,1,1201,4,Female,50,3,5,Manager,3,Divorced,18606,18640,3,Y,No,18,3,2,80,1,26,6,3,7,7,4,7
946,40,Yes,Travel_Rarely,299,Sales,25,4,Marketing,1,1318,4,Male,57,2,3,Sales Executive,2,Single,9094,17235,2,Y,Yes,12,3,3,80,0,9,2,3,5,4,1,0

In [7]:
# Dataset Dimensions to Determine the number of observations and variables contained in the dataset.

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 1470
Columns: 35

The dataset contains **1,470 employee records** and **35 variables** showing employee demographics, job characteristics, compensation, work environment, and attrition status.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

#### Statistical/Categorical Summary 
To provides insights into employee characteristics such as age, income, years at the company, total working years, job role, marital status, department, and education field.

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1470.00,36.92,9.14,18.00,30.00,36.00,43.00,60.00
DailyRate,1470.00,802.49,403.51,102.00,465.00,802.00,1157.00,1499.00
DistanceFromHome,1470.00,9.19,8.11,1.00,2.00,7.00,14.00,29.00
Education,1470.00,2.91,1.02,1.00,2.00,3.00,4.00,5.00
EmployeeCount,1470.00,1.00,0.00,1.00,1.00,1.00,1.00,1.00
EmployeeNumber,1470.00,1024.87,602.02,1.00,491.25,1020.50,1555.75,2068.00
EnvironmentSatisfaction,1470.00,2.72,1.09,1.00,2.00,3.00,4.00,4.00
HourlyRate,1470.00,65.89,20.33,30.00,48.00,66.00,83.75,100.00
JobInvolvement,1470.00,2.73,0.71,1.00,2.00,3.00,3.00,4.00
JobLevel,1470.00,2.06,1.11,1.00,1.00,2.00,3.00,5.00
JobSatisfaction,1470.00,2.73,1.10,1.00,2.00,3.00,4.00,4.00
MonthlyIncome,1470.00,6502.93,4707.96,1009.00,2911.00,4919.00,8379.00,19999.00
MonthlyRate,1470.00,14313.10,7117.79,2094.00,8047.00,14235.50,20461.50,26999.00
NumCompaniesWorked,1470.00,2.69,2.50,0.00,1.00,2.00,4.00,9.00
PercentSalaryHike,1470.00,15.21,3.66,11.00,12.00,14.00,18.00,25.00
PerformanceRating,1470.00,3.15,0.36,3.00,3.00,3.00,3.00,4.00
RelationshipSatisfaction,1470.00,2.71,1.08,1.00,2.00,3.00,4.00,4.00
StandardHours,1470.00,80.00,0.00,80.00,80.00,80.00,80.00,80.00
StockOptionLevel,1470.00,0.79,0.85,0.00,0.00,1.00,1.00,3.00
TotalWorkingYears,1470.00,11.28,7.78,0.00,6.00,10.00,15.00,40.00
TrainingTimesLastYear,1470.00,2.80,1.29,0.00,2.00,3.00,3.00,6.00
WorkLifeBalance,1470.00,2.76,0.71,1.00,2.00,3.00,3.00,4.00
YearsAtCompany,1470.00,7.01,6.13,0.00,3.00,5.00,9.00,40.00
YearsInCurrentRole,1470.00,4.23,3.62,0.00,2.00,3.00,7.00,18.00
YearsSinceLastPromotion,1470.00,2.19,3.22,0.00,0.00,1.00,3.00,15.00
YearsWithCurrManager,1470.00,4.12,3.57,0.00,2.00,3.00,7.00,17.00

In [13]:
df.describe(include='object').T

               count unique                     top  freq
Attrition       1470      2                      No  1233
BusinessTravel  1470      3           Travel_Rarely  1043
Department      1470      3  Research & Development   961
EducationField  1470      6           Life Sciences   606
Gender          1470      2                    Male   882
JobRole         1470      9         Sales Executive   326
MaritalStatus   1470      3                 Married   673
Over18          1470      1                       Y  1470
OverTime        1470      2                      No  1054

In [14]:
# Missing Value Assessment

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().mean()*100).round(2)
})

missing

                          Missing Values  Percentage
Age                                    0        0.00
Attrition                              0        0.00
BusinessTravel                         0        0.00
DailyRate                              0        0.00
Department                             0        0.00
DistanceFromHome                       0        0.00
Education                              0        0.00
EducationField                         0        0.00
EmployeeCount                          0        0.00
EmployeeNumber                         0        0.00
EnvironmentSatisfaction                0        0.00
Gender                                 0        0.00
HourlyRate                             0        0.00
JobInvolvement                         0        0.00
JobLevel                               0        0.00
JobRole                                0        0.00
JobSatisfaction                        0        0.00
MaritalStatus                          0        0.00
MonthlyIncome                          0        0.00
MonthlyRate                            0        0.00
NumCompaniesWorked                     0        0.00
Over18                                 0        0.00
OverTime                               0        0.00
PercentSalaryHike                      0        0.00
PerformanceRating                      0        0.00
RelationshipSatisfaction               0        0.00
StandardHours                          0        0.00
StockOptionLevel                       0        0.00
TotalWorkingYears                      0        0.00
TrainingTimesLastYear                  0        0.00
WorkLifeBalance                        0        0.00
YearsAtCompany                         0        0.00
YearsInCurrentRole                     0        0.00
YearsSinceLastPromotion                0        0.00
YearsWithCurrManager                   0        0.00

This shows that dataset contains no missing values, indicating that all observations are complete and no imputation is required at this stage.

In [15]:
# Duplicate Records

duplicates = df.duplicated().sum()

print(f"Duplicate Records: {duplicates}")

Duplicate Records: 0

In [16]:
# Data Type to determine whether each variable has an appropriate data type.

df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [17]:
# Number of Unique Values to identify identifier variables, constant variables, and categorical features that may require encoding during model development.

df.nunique().sort_values()

Over18                         1
StandardHours                  1
EmployeeCount                  1
Gender                         2
Attrition                      2
PerformanceRating              2
OverTime                       2
MaritalStatus                  3
Department                     3
BusinessTravel                 3
StockOptionLevel               4
EnvironmentSatisfaction        4
JobInvolvement                 4
JobSatisfaction                4
RelationshipSatisfaction       4
WorkLifeBalance                4
Education                      5
JobLevel                       5
EducationField                 6
TrainingTimesLastYear          7
JobRole                        9
NumCompaniesWorked            10
PercentSalaryHike             15
YearsSinceLastPromotion       16
YearsWithCurrManager          18
YearsInCurrentRole            19
DistanceFromHome              29
YearsAtCompany                37
TotalWorkingYears             40
Age                           43
HourlyRate                    71
DailyRate                    886
MonthlyIncome               1349
MonthlyRate                 1427
EmployeeNumber              1470
dtype: int64

In [19]:
# Constant Features 

constant_columns = [col for col in df.columns if df[col].nunique() == 1]

constant_columns

['EmployeeCount', 'Over18', 'StandardHours']

The identified variables contain only a single unique value across all observations.

In [21]:
# Identifier Variables 

df["EmployeeNumber"].nunique()

1470

`EmployeeNumber` uniquely identifies each employee and serves as an identifier rather than a predictive feature. It will be excluded during model development.

In [25]:
# Target Variable Inspection

df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [23]:
(df["Attrition"].value_counts(normalize=True) * 100).round(2)

Attrition
No    83.88
Yes   16.12
Name: proportion, dtype: float64

The target variable is imbalanced, with significantly more employees remaining in the organization than leaving. This imbalance should be considered during model development and evaluation.

In [26]:
# Data Quality Assessment Summary

summary = pd.DataFrame({
    "Assessment": [
        "Missing Values",
        "Duplicate Records",
        "Constant Columns",
        "Identifier Column",
        "Target Variable"
    ],
    "Result": [
        missing["Missing Values"].sum(),
        duplicates,
        len(constant_columns),
        "EmployeeNumber",
        "Attrition"
    ]
})

summary

          Assessment          Result
0     Missing Values               0
1  Duplicate Records               0
2   Constant Columns               3
3  Identifier Column  EmployeeNumber
4    Target Variable       Attrition

#### Data Cleaning Decisions

Based on the data quality assessment, the following decisions were made:

- No missing values were detected.
- No duplicate records were identified.
- Three constant variables were identified.
- EmployeeNumber is a unique identifier and will be excluded during feature engineering.
- No datatype inconsistencies were observed.
- The dataset is suitable for Exploratory Data Analysis (EDA).

#### Initial Observations

The dataset is clean, complete, and well-structured for analysis. Most variables are suitable for exploratory analysis, while a few constant and identifier variables have been documented for removal during feature engineering. The target variable exhibits class imbalance, which should be considered during the modeling stage.

In [27]:
df.to_csv("clean_employee_attrition.csv", index=False)

Exploratory Data Analysis (EDA) In this project, aims to identify factors influencing employee attrition and provide data-driven insights to support retention strategies.